import { CrossSelling } from "./cross-selling";
import { Entity } from "./entity";
import { GalleryImage } from "./gallery-image";
import { List } from "./list";
import { PrincipalImage } from "./principal-image";
import { SubCategory } from "./sub-category";
import { SupplierItem } from "./supplier-item";
import { UpSelling } from "./up-selling";
import { Vademecum } from "./vademecum";
import { Option } from './option';

export class Product extends Entity{
    principalImageGuid?: string;
    name?: string;
    description?: string;
    stock?: number;
    minimumStock?: number;
    unitPrice?: number;
    brand?: string;
    mainComponent?: string;
    drug?: string;
    action?: string;
    presentation?: string;
    routesOfAdministration?: string;
    milkWithdrawal?: string;
    meatRecall?: string;
    discontinued?: boolean;
    missingInformation?: boolean;
    missingFoto?: boolean;
    oBS?: string;
    crossSellingGuid?: string;
    upSellingGuid?: string;
    vademecumGuid?: string;
    subCategoryGuid?: string;
    listGuid?: string;
    laboratoryGuid?: string;
    supplierItemGuid?: string;
    crossSelling?: CrossSelling;
    upSelling?: UpSelling;
    principalImage?: PrincipalImage;
    vademecum?: Vademecum;
    subCategory?: SubCategory;
    list?: List;
    supplierItem?: SupplierItem;
    totalPrice?: number;
    categoryGuids?: string[];
    kindGuids?: string[];
    lineGuids?: string[];
    categories?: Option[];
    kinds?: Option[];
    lines?: Option[];
    galleryImages?: GalleryImage[];
}